version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: neuro
      POSTGRES_PASSWORD: capture
      POSTGRES_DB: neurocapture
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
