"""initial full schema

Revision ID: 45ec1e521775
Revises: 
Create Date: 2025-05-18 14:21:41.653756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ec1e521775'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_subscores',
    sa.Column('subscore_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['cognitive_assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscore_id')
    )
    op.create_index(op.f('ix_assessment_subscores_subscore_id'), 'assessment_subscores', ['subscore_id'], unique=False)
    op.drop_constraint('cognitive_assessments_patient_id_fkey', 'cognitive_assessments', type_='foreignkey')
    op.create_foreign_key(None, 'cognitive_assessments', 'patients', ['patient_id'], ['patient_id'], ondelete='CASCADE')
    op.drop_constraint('demographics_patient_id_fkey', 'demographics', type_='foreignkey')
    op.create_foreign_key(None, 'demographics', 'patients', ['patient_id'], ['patient_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demographics', type_='foreignkey')
    op.create_foreign_key('demographics_patient_id_fkey', 'demographics', 'patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'cognitive_assessments', type_='foreignkey')
    op.create_foreign_key('cognitive_assessments_patient_id_fkey', 'cognitive_assessments', 'patients', ['patient_id'], ['patient_id'])
    op.drop_index(op.f('ix_assessment_subscores_subscore_id'), table_name='assessment_subscores')
    op.drop_table('assessment_subscores')
    # ### end Alembic commands ###
